### PR TITLE
noloop gif should be -1

### PR DESCRIPTION
**Pull request by Leetcore**
repeat	0	repeat count, -1 = no repeat, 0 = forever
https://github.com/jnordberg/gif.js

### CODE REVIEW

**Comment by Leetcore** [comment]
-1 is no repeat. Would be first image?! I don't know why its not working here...

**Comment by Leetcore** [comment]
Wow this is tricky.

Chrome and Firefox Dev loops it twice.

**Comment by juliandescottes** [comment]
Ah thanks for fixing this!

**Comment by juliandescottes** [comment]
Just restarted the CI tests, sometimes phantom crashes, most likely has nothing to do with your patch.

**Comment by juliandescottes** [comment]
Tests are passing. Thanks a lot @Leetcore

**Pull request merged**
