### PR TITLE
fix(build): update deps, karma and nw config

### PR DESCRIPTION
**Pull request by ayushmxn**
Fixes: #973, #1047
Closes: #1013, #1041

## Changes

- Allow installation of `node_modules` on Node 14 and above [`11e0066`](https://github.com/piskelapp/piskel/commit/11e00664dde66a556fc128bdbaaadd62294ae3a2)
- Switch to Chromium Headless with Karma to successfully run tests [`9bbc9d2`](https://github.com/piskelapp/piskel/pull/1049/commits/9bbc9d241d9964f69b9e8741d5db078733657f21)
- ~Use a fork of grunt nw plugin to get desktop builds working [`bb4c4fe`](https://github.com/piskelapp/piskel/pull/1049/commits/bb4c4fe66639e147665b5998efb49d2f5f66f5a2)~
- Replace `build` and `build:mac` commands with `desktop:run` and `desktop:build` (for all platforms except osx32).

## Build Instructions

- Using your package manager of choice, `desktop:run` to run the desktop app directly.
- `desktop:build` to build applications for all platforms except `osx32`.

I'll be making a bunch of fixes in this branch and release them at https://ayushmxn.github.io/piskel

## Things yet to be done

- Update IndexedDB implementation to get tests passing again
- Rewrite CLI using `yargs`
- Update code until possible to remove Phantom dependency

> If you're able to, I'd urge you to use [Aseprite](https://www.aseprite.org/) instead.

### CODE REVIEW

**Comment by gingerbeardman** [comment]
Thanks for your work on this!

The build system now works. 

However, the current build for macOS is broken due to problems with old NW.js on latest macOS. So I needed to make one more change, to increase the version of nwjs:

```
macos : {
  options: {
    downloadUrl: 'https://dl.nwjs.io/',
    osx64: true,
    version : "0.63.1",
    build_dir: './dest/desktop/',
    flavor: "normal",
  },
  src: ['./dest/prod/**/*', "./package.json", "!./dest/desktop/"]
},
```

**Comment by ayushmxn** [comment]
> Thanks for your work on this!
> 
> The build system now works.
> 
> However, the current build for macOS is broken due to problems with old NW.js on latest macOS. So I needed to make one more change, to increase the version of nwjs:
> 
> ```
> macos : {
>   options: {
>     downloadUrl: 'https://dl.nwjs.io/',
>     osx64: true,
>     version : "0.63.1",
>     build_dir: './dest/desktop/',
>     flavor: "normal",
>   },
>   src: ['./dest/prod/**/*', "./package.json", "!./dest/desktop/"]
> },
> ```

Good to know! I don't use Macs which is probably why I missed this. I'll make the change later today.

**Comment by gingerbeardman** [comment]
I'd like to make some changes for quality of life improvements, such as a preference to switch off warning messages and different defaults depending in the filename.

I am familiar with JavaScript, but what is the main thing I will need to read up on to be able to edit work with this codebase?

**Comment by ayushmxn** [comment]
I'm not sure what could act as a good reference. From what I've seen, the codebase is pretty old - there's a polyfill for Promises and the underlying browser APIs have also changed. It looks like the maintainer is not active anymore so making my changes on a [forked version](https://github.com/ayushmxn/piskel).

**Comment by ayushmxn** [comment]
@gingerbeardman If you're looking for something production ready, this is not it. It'll probably take me 1-2 months to get everything working.

**Comment by gingerbeardman** [comment]
Hey no worries! I'm not in a rush and I'm happy enough with my butchered version for now. 

My current issue: on the import dialog I'm setting framesize from values in the filename (eg. `image-table-16-32.png`) but I can't get the grid to display without user input (tabbing to another field).

Is there anywhere we can chat about these things? This issue seems to not be the best place. @ayushmxn

**Comment by gingerbeardman** [comment]
@ayushmxn i've contacted you on https://gitter.im

**Comment by dginovker** [comment]
@bcharbonnier Could you add @ayushmxn as a maintainer? I'm trying to package piskel as a Flatpak and this PR is basically essential for it. Without the PR I would have to package his version, which is weird

**Comment by dginovker** [comment]
Well this was mighty unfortunate.

**Comment by ayushmxn** [comment]
Closed the PR since didn't look like it was going to be merged so forked the repo and maintaining my own version here:
https://github.com/pahuch/piskel

**Comment by tharatau** [comment]
@NiasuK You can apply the patches in this PR and test it out - will probably have to update bunch of deps again. I used to maintain a fork but deleted it a while ago - moved on to other things.

**Pull request closed without merging**
