### PR TITLE
Croptool

### PR DESCRIPTION
**Pull request by juliandescottes**

### CODE REVIEW

**Comment by juliandescottes** [comment]
First implementation of the crop tool:

piskel-crop-tool

**Comment by juliandescottes** [comment]
By default the crop will fit the content. If there is a current selection, it will crop to the selection instead.

**Comment by poorvasingal** [comment]
Wow Julian!! This looks so great. Thank you for implementing this!

**Comment by caleybrock** [comment]
This is awesome - students and teachers will be so appreciative! Thanks so much for implementing. I'm looking forward to getting it into Game Lab!

**Comment by juliandescottes** [comment]
Thanks for the nice feedback :) Let's merge this.

**Pull request merged**
